auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: qiaohezi.github.io
url: http://qiaohezi.github.io
feed: /atom.xml
author_info: <a href="http://qiaohezi.github.io/">Dean</a>
